### DISCUSSION TITLE
Struggling with Streams (i think...)

### DISCUSSION THREAD

**Discussion by takigama** [rtbrick/bngblaster#318] [Q&A] [answered]
Hi All,

I have a config that spins up a bunch of dhcp and pppoe subscribers and all I was after from streams is to send 1 pps from each subscriber to something upstream of the BNG. I've simplified the config down to this (bgplink0 is a layer 2 interface into the access network):

```yaml
{
    "interfaces": {
        "access": [
        {
            "interface": "bnglink0",
            "type": "ipoe",
            "outer-vlan-min": 3089,
            "outer-vlan-max": 3701,
            "outer-vlan-step": 1,
            "inner-vlan-min": 11,
            "inner-vlan-max": 4011,
            "inner-vlan-step": 1,
            "stream-group-id": 1
        }
    ]
    },
    "dhcp": {
        "enable": true
    },
    "dhcpv6": {
        "enable": false
    },
    "access-line": {
        "agent-remote-id": "AVC.{session-global}",
        "agent-circuit-id": "et-7/0/1:{session-global}"
    },
    "sessions": {
            "start-rate": 100,
            "max-outstanding": 40000
    },
    "streams": [
            {
            "stream-group-id": 1,
            "name": "S1",
            "direction": "upstream",
            "pps": 1,
            "type": "ipv4",
            "destination-ipv4-address": "10.241.0.1"
    }
    ]
}
```

So far, all I can get out of it is:
Mar 18 15:15:13.772994 Failed to build packet for stream S1

So im not sure if im miss-understanding the purpose of streams or using them wrong or supposed to be using something other than streams??

**Comment by GIC-de** [comment]
It failed to create traffic because there is no network-interface which could receive the traffic.

**Reply by takigama** [reply]
Thanks for the reply..

Ok, some of the config's have things like this on them (which I dont have):
```yaml
{
    "interfaces": {
        "network": {
            "interface": "eth2",
            "address": "10.0.0.1/24",
            "gateway": "10.0.0.2",
            "address-ipv6": "fc66:1337:7331::1/64",
            "gateway-ipv6": "fc66:1337:7331::2"
        },
...
```

and my stream config is like this:
```yaml
 "streams": [
            {
            "stream-group-id": 1,
            "name": "S1",
            "direction": "upstream",
            "pps": 1,
            "type": "ipv4",
            "destination-ipv4-address": "10.241.0.1"
    }
```

I was hoping the the streams would originate from the dhcp/pppoe clients (i.e. if im running up 10k each of pppoe/ipoe, each client would send 1pps to 10.241.0.1 and 10.241.0.1 should see about 20k pps of traffic from 20k addresses).  But if I read what you're saying, traffic streams come from the "network" interface? Though the doco suggests that bounded streams should bound to the clients and raw streams come from "network" interfaces, but maybe i've miss-understood that?.

Or is it that the bng blaster itself HAS to be the receiver for the traffic (even though i've over-written the destination ip) and the bngblaster needs a layer 3 interface upstream of the clients? Currently bngblaster only has a layer2 in the access network and the layer 3 interface is via a completely different network that the access network has no connectivity into.

If its the latter, Is there an alternative for traffic generation from the access clients? I really just want them to generate traffic, dont really need to receive it in any way as such.
