### ISSUE TITLE
running isis instance ist not shown when retrieving /metrics from bng-blaster-controller rest API

### ISSUE THREAD

**Issue by slieberth** [rtbrick/bngblaster#139]
**Describe the bug**

Hi Christian,
thanks for providing bng Blaster, run first test and isis adjacency came up instantaneously ;-)
Maybe my expectation is wrong, but a running isis instance should be taken into calculation when retrieving /metrics ...

**To Reproduce**

Version (`bngblaster -v`):

```
sli@sli-Standard-PC-i440FX-PIIX-1996:~$ sudo bngblaster -v
Version: 0.8.8
Compiler: GNU (9.4.0)
IO Modes: packet_mmap_raw (default), packet_mmap, raw
```

JSON configuration:
```json
{
    "interfaces": {
        "network": [
            {
                "interface": "ens9",
                "address": "192.168.122.27/24",
                "gateway": "192.168.122.11",
                "address-ipv6": "fc66:1337:7331:2::2/64",
                "gateway-ipv6": "fc66:1337:7331:2::1",
                "isis-instance-id": 1
            }
        ]
    },
    "isis": [
        {
            "instance-id": 1,
            "system-id": "0100.1001.0010",
            "router-id": "10.10.10.10",
            "hostname": "R1",
            "area": [
                "49.0001/24",
                "49.0002/24"
            ],
            "hello-padding": true,
            "lsp-lifetime": 65535
        }
    ]
}
```

1. start bng blaster

```
sli@sli-Standard-PC-i440FX-PIIX-1996:~$ sudo bngblaster -C isis_bngblst.yml -L test.log -l ip -l isis -l bgp
[sudo] password for sli: 
Jan 09 20:57:03.783963 Init IS-IS instance 1
Jan 09 20:57:03.790842 Add network interface ens9 to IS-IS instance 1
Jan 09 20:57:03.794949 ISIS L1 adjacency UP to 0255.0001.0002 on interface ens9 
Jan 09 20:57:03.795138 ISIS L2 adjacency UP to 0255.0001.0002 on interface ens9 
Jan 09 20:57:04.791165 Resolve network interfaces
Jan 09 20:57:05.793889 Resolve network interfaces
Jan 09 20:57:06.794357 Resolve network interfaces
```
2. retrieve http://192.168.101.139:8001/metrics

```
request:
  headers:
    Accept: '*/*'
    Accept-Encoding: gzip, deflate
    Connection: keep-alive
    User-Agent: python-requests/2.22.0
  method: GET
  url: http://192.168.101.139:8001/metrics
response:
  headers:
    Content-Encoding: gzip
    Content-Length: '157'
    Content-Type: text/plain; version=0.0.4; charset=utf-8
    Date: Mon, 09 Jan 2023 19:57:26 GMT
  reason: OK
  status_code: 200
  text: '# HELP instances_running The number of running instances
    # TYPE instances_running gauge
    instances_running{hostname="sli-Standard-PC-i440FX-PIIX-1996"} 0
    # HELP instances_total The total number of instances
    # TYPE instances_total gauge
    instances_total{hostname="sli-Standard-PC-i440FX-PIIX-1996"} 0
```

**Expected behavior**

json shows the runing instance
    instances_running{hostname="sli-Standard-PC-i440FX-PIIX-1996"} 1

**Screenshots**

**Additional context**

please treat as low priority ...
